### ISSUE TITLE
Redesign the website to make it more appealing to potential users.

### ISSUE THREAD

**Issue by gohanko** [SuperTux/htdocs#5]
I noticed the website looks a bit 2003, and I wonder if we could redesign the site? Maybe add a landing page on it with some of the other pages there such as blogs.

**Comment by gohanko** [comment]
Why no framework? It is much easier to build using bootstrap than to do it by hand

**Comment by maxteufel** [comment]
Frameworks tend to be bloated and pull in even more dependencies (i.e. jQuery or FontAwesome). Bloat increases load times in exchange for things that you often don't use. Depending on JavaScript for often simple things that can be done otherwise also seems silly (and unwanted if you're paranoid).

**Comment by gohanko** [comment]
Fair enough.

**Comment by maxteufel** [comment]
Also as I said - "ideally" - if absolutely necessary a small framework is probably fine.

**Comment by gohanko** [comment]
The desktop version of the site looks great but on mobile its a bit weird.
